// Curation → code: regenerate shared/fabricator/style-refs.ts from chosen
// reference images.
//
// Usage: npx tsx scripts/embed-style-refs.ts vehicle=fixtures/art/dune-runner.png tool=fixtures/art/timber-axe.png structure=fixtures/art/stone-hut.png
//
// The refs must be importable by the Cloudflare worker, which has no
// filesystem — so they live as base64 constants in a generated module. The
// palette clause for the prompt is derived here too, from the refs
// themselves: the palette the style actually uses, not the one we wish it
// used. Refs are keyed down to ≤160px before embedding — the model needs the
// style, not the resolution, and the worker bundle carries every byte.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { decodePng, encodePng, makeImage } from "./lib/png";
import { keyImage } from "../client/src/screen/chroma-core";

const CATEGORIES = ["vehicle", "structure", "tool"] as const;
const MAX_REF_SIDE = 160;

const args = process.argv.slice(2);
if (args.length === 0) {
  console.error(
    "usage: npx tsx scripts/embed-style-refs.ts vehicle=<png> structure=<png> tool=<png>\n" +
      "(any subset; existing refs for unmentioned categories are dropped)",
  );
  process.exit(1);
}

const chosen = new Map<string, string>();
for (const a of args) {
  const [cat, file] = a.split("=");
  if (!CATEGORIES.includes(cat as (typeof CATEGORIES)[number]) || !file) {
    console.error(`bad argument: ${a}`);
    process.exit(1);
  }
  chosen.set(cat, file);
}

const refs: Record<string, { source: string; base64: string }> = {};
const paletteCounts = new Map<string, number>();

for (const [cat, file] of chosen) {
  const img = decodePng(readFileSync(file));

  // Key the background out so the embedded ref carries the subject alone —
  // a magenta field in the reference would teach the model that magenta
  // fields are part of the style.
  keyImage(img.data, img.width, img.height);

  // Downscale to the embed budget.
  const scale = Math.min(1, MAX_REF_SIDE / Math.max(img.width, img.height));
  const w = Math.max(1, Math.round(img.width * scale));
  const h = Math.max(1, Math.round(img.height * scale));
  const small = makeImage(w, h);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const s = (Math.floor(y / scale) * img.width + Math.floor(x / scale)) * 4;
      small.data.set(img.data.subarray(s, s + 4), (y * w + x) * 4);
    }
  }

  // Palette: quantise opaque pixels to 32-steps and count.
  for (let i = 0; i < w * h; i++) {
    if (small.data[i * 4 + 3] < 200) continue;
    const q = (v: number) => Math.round(v / 32) * 32;
    const key = `#${[q(small.data[i * 4]), q(small.data[i * 4 + 1]), q(small.data[i * 4 + 2])]
      .map((v) => Math.min(255, v).toString(16).padStart(2, "0"))
      .join("")}`;
    paletteCounts.set(key, (paletteCounts.get(key) ?? 0) + 1);
  }

  refs[cat] = { source: file.replace(/^.*fixtures\//, "fixtures/"), base64: encodePng(small).toString("base64") };
  console.log(`${cat}: ${file} → ${w}x${h}, ${Math.round(refs[cat].base64.length / 1024)}KB embedded`);
}

const palette = [...paletteCounts.entries()]
  .sort((a, b) => b[1] - a[1])
  .slice(0, 10)
  .map(([hex]) => hex);

const out = `// GENERATED by scripts/embed-style-refs.ts — do not edit by hand.
//
// Style-reference images for body-sprite generation: our own best generated
// outputs, curated from the eval-art contact sheet, one per category. The
// image prompt passes the matching ref with "match this exact rendering
// style". See scripts/embed-style-refs.ts for how to re-curate.
//
// ISOMORPHIC — imported by the worker; base64 constants, no fs.

import type { FabricatedSpec } from "./schema";

export type StyleRef = {
  /** Where this ref came from, for humans. */
  source: string;
  /** PNG, raw base64 (no data: prefix). */
  base64: string;
};

export const STYLE_REFS: Partial<Record<FabricatedSpec["category"], StyleRef>> = {
${Object.entries(refs)
  .map(
    ([cat, r]) =>
      `  ${cat}: {\n    source: ${JSON.stringify(r.source)},\n    base64:\n      ${JSON.stringify(r.base64)},\n  },`,
  )
  .join("\n")}
};

/** The palette the curated refs actually use, most-common first. */
export const STYLE_PALETTE: string[] = ${JSON.stringify(palette)};
`;

const target = fileURLToPath(new URL("../shared/fabricator/style-refs.ts", import.meta.url));
writeFileSync(target, out);
console.log(`\nwrote ${target}`);
console.log(`palette: ${palette.join(" ")}`);
